### ISSUE TITLE
pg-promise bad misuse

### ISSUE THREAD

**Issue by vitaly-t** [ashermcoa/realtime_multiplayer_game#1]
What you are doing in your code, calling this:
```js
pgp.end(); // for immediate app exit, closing the connection pool
```
after every request, is a terrible, terrible idea.

You are shutting down the complete connection pool and shutting down all database communications on every HTTP request to the database. That's just awful.

Look at the documentation again, this method is there only for some special cases, like running a single script that needs to exit automatically. This method isn't for web apps at all.

**Comment by mazho** [comment]
Many thanks. I wrote this code when starting on pg-promise. i will re-write the whole thing

**Comment by vitaly-t** [comment]
The whole thing? That sounds dramatic :) Anyhow, that's not what I was suggesting :)

**Comment by ashermcoa** [comment]
I mean the code needs some modularity. That's why I have to re-write a bunch of stuffs in there

**Comment by vitaly-t** [comment]
The best pattern you can find is here - [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo) ;)

**Comment by ashermcoa** [comment]
Sure. Very helpful

**Comment by ashermcoa** [comment]
Fixed. Will do modularity part later

**Comment by vitaly-t** [comment]
And in case you like TypeSctipts, the [library's TypeScript](https://github.com/vitaly-t/pg-promise/tree/master/typescript)  is now a joy to use ;)

**Comment by ashermcoa** [comment]
Sure. I will look at that :-) Looks great
